Mac m1/m2 'terraform init' issue resolved
while executing terraform init you might face the below error if you are working in a MAC with M1 or M2 chip in it,

Error: Incompatible provider version

│ Provider Terraform Registry 95 v2.2.0 does not have a
│ package available for your current platform, darwin_arm64.


ISSUE RESOLVED !!!